name: Build Feature Branch

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!fix/[0-9]+.[0-9]+.x'

jobs:
  branch:
    uses: onecx-apps/ci-quarkus/.github/workflows/build-branch.yml@v0-jdk17
    secrets: inherit